{% set name = "smee" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/smee/archive/{{ version }}.tar.gz
  sha256: 6105780c69834e970fb18cb3fbb298dc8f855aa432d716c9a4f2aeefbdce1e9d

build:
  number: 0

outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.10
        - pip
        - versioningit
        - openff-units
        - openff-toolkit-base >=0.9.2
        - openff-interchange-base >=0.3.17
        - pytorch
        - nnpops
      run:
        - python >=3.10
        - openff-units
        - openff-toolkit-base >=0.9.2
        - openff-interchange-base >=0.3.17
        - pytorch  # [unix]
        - nnpops
        - __unix  # [unix]
    test:
      imports:
        - smee

  - name: {{ name|lower }}
    build:
      noarch: python
    requirements:
      host:
        - python >=3.10
      run:
        - python >=3.10
        - {{ pin_subpackage('smee-base', exact=True) }}
        # md simulations
        - openmm
        - packmol
        - numpy
        - msgpack-python
        - pydantic
        # included for convenience so that the openff toolkit can
        # parameterize molecules without needing extra installs
        - rdkit
        - ambertools  # [unix]
        - __unix  # [unix]
    test:
      imports:
        - smee

about:
  home: https://github.com/SimonBoothroyd/smee
  summary: 'Differentiably evaluate energies using SMIRNOFF force fields'
  description: |
    A framework that aims to offer a simple API for differentiably evaluating 
    the energy of SMIRNOFF force fields applied to molecules using pytorch.
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_3RD_PARTY
  doc_url: https://github.com/SimonBoothroyd/smee
  dev_url: https://github.com/SimonBoothroyd/smee

extra:
  recipe-maintainers:
    - SimonBoothroyd
