{% set name = "smee" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/smee/archive/{{ version }}.tar.gz
  sha256: f54067402f2e0e0b312c0e007aba5681944de4ebd091b55db42181bfcd58c9fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioningit
  run:
    - python >=3.10
    - openff-units
    - openff-toolkit-base >=0.9.2
    - openff-interchange-base >=0.3.14
    - pytorch  # [unix]
    - pydantic
    # included for convenience so that the openff toolkit can 
    # parameterize molecules without needing extra installs
    - rdkit
    - ambertools  # [unix]
    - __unix  # [unix]
test:
  imports:
    - smee

about:
  home: https://github.com/SimonBoothroyd/smee
  summary: 'Differentiably evaluate energies using SMIRNOFF force fields'
  description: |
    A framework that aims to offer a simple API for differentiably evaluating 
    the energy of SMIRNOFF force fields applied to molecules using pytorch.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/SimonBoothroyd/smee
  dev_url: https://github.com/SimonBoothroyd/smee

extra:
  recipe-maintainers:
    - SimonBoothroyd
